name: PUBLISH

on:
  push:
    tags:
      - v*

jobs:

  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install pdm

      - name: Build
        run: |
          pdm install
          pdm build

      - name: Publish
        env:
          PYPI_USERNAME: __token__
          PYPI_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          pdm set
          pdm publish --repository pypi
          pdm config repository.pypi.password "$PYPI_PASSWORD"
